# Generated by Django 6.0.1 on 2026-02-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
        ('surveys', '0018_alter_foto_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informe',
            name='foto',
        ),
        migrations.AddField(
            model_name='informe',
            name='fotos',
            field=models.ManyToManyField(blank=True, to='surveys.foto'),
        ),
    ]
