# Generated by Django 6.0.1 on 2026-05-05 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('dni', models.CharField(max_length=20)),
                ('enrollment_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollees', to='enrollments.enrollmentlist')),
            ],
        ),
        migrations.CreateModel(
            name='ListField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('enrollment_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='enrollments.enrollmentlist')),
            ],
        ),
        migrations.CreateModel(
            name='EnrolleeFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('enrollee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='enrollments.enrollee')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollments.listfield')),
            ],
            options={
                'unique_together': {('enrollee', 'field')},
            },
        ),
    ]
