# Generated by Django 6.0.1 on 2026-05-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Texto Corto'), ('number', 'Número'), ('date', 'Fecha'), ('email', 'Correo Electrónico')], default='text', max_length=20),
        ),
    ]
