# Generated by Django 6.0.1 on 2026-05-06 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_listfield_field_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollee',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='enrollee',
            name='full_name',
        ),
    ]
