# Generated by Django 6.0.1 on 2026-05-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_importjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importjob',
            name='enrollment_list',
        ),
        migrations.AddField(
            model_name='enrollee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollee',
            name='dynamic_data',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='EnrolleeFieldValue',
        ),
        migrations.DeleteModel(
            name='ImportJob',
        ),
    ]
