# Generated by Django 6.0.1 on 2026-05-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0005_remove_importjob_enrollment_list_enrollee_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listfield',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='listfield',
            name='is_searchable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listfield',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listfield',
            name='label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='listfield',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
