# Generated by Django 6.0.1 on 2026-05-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0006_alter_listfield_options_listfield_is_searchable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentlist',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='listfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Texto Corto'), ('number', 'Número'), ('date', 'Fecha'), ('email', 'Correo Electrónico')], default='text', max_length=50),
        ),
        migrations.AlterField(
            model_name='listfield',
            name='label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='listfield',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
