# Generated by Django 6.0.1 on 2026-05-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0007_alter_enrollmentlist_name_alter_listfield_field_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentlist',
            name='ui_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
