# Generated by Django 6.0.1 on 2026-05-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0009_person_enrollee_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_affiliate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
