# Generated by Django 6.0.1 on 2026-05-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0010_person_is_affiliate_person_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(default='USHUAIA', max_length=255),
        ),
    ]
