# Generated by Django 6.0.1 on 2026-05-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0011_person_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentlist',
            name='last_import_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='enrollmentlist',
            name='last_import_status',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
