# Generated by Django 6.0.5 on 2026-05-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0013_person_age_person_employment_status_person_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='workplace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
