# Generated by Django 6.0.5 on 2026-05-25 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0014_person_workplace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionCumpleanos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año del cumpleaños')),
                ('entregado', models.BooleanField(default=False, verbose_name='¿Información entregada?')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Empleado asignado')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cumpleanos_asignados', to='enrollments.person')),
            ],
            options={
                'verbose_name': 'Asignación de Cumpleaños',
                'verbose_name_plural': 'Asignaciones de Cumpleaños',
                'constraints': [models.UniqueConstraint(fields=('persona', 'anio'), name='unico_cumpleanos_por_persona_y_anio')],
            },
        ),
    ]
