# Generated by Django 6.0.5 on 2026-05-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0015_asignacioncumpleanos'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacioncumpleanos',
            name='observacion_resuelta',
            field=models.BooleanField(default=False, verbose_name='¿Observación resuelta?'),
        ),
    ]
