# Generated by Django 6.0.1 on 2026-01-23 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('es_relevamiento', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('orden', models.IntegerField(default=0)),
                ('tipo', models.CharField(choices=[('texto', 'Texto Libre'), ('numero', 'Numérico'), ('opciones', 'Opciones'), ('foto', 'Foto')], default='texto', max_length=20)),
                ('opciones', models.JSONField(blank=True, help_text='Lista de opciones ej: ["Si", "No"]', null=True)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='surveys.encuesta')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('seccion', models.CharField(blank=True, max_length=100, null=True)),
                ('barrio', models.CharField(blank=True, max_length=100, null=True)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='surveys.encuesta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas_respondidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.TextField(blank=True, null=True)),
                ('valor_numero', models.FloatField(blank=True, null=True)),
                ('valor_foto', models.ImageField(blank=True, null=True, upload_to='respuestas_fotos/')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_recibidas', to='surveys.pregunta')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='surveys.respuestaheader')),
            ],
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barrios', to='surveys.seccion')),
            ],
            options={
                'unique_together': {('nombre', 'seccion')},
            },
        ),
    ]
