# Generated by Django 6.0.1 on 2026-01-26 08:30

import surveys.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='requiere_ubicacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='activa',
            field=models.BooleanField(default=True, help_text='Si es False, la pregunta no se muestra pero no se borran sus datos.'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='obligatoria',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='respuestadetalle',
            name='valor_foto',
            field=models.ImageField(blank=True, null=True, upload_to=surveys.models.generar_ruta_imagen),
        ),
    ]
