# Generated by Django 6.0.1 on 2026-01-27 05:47

import django.db.models.deletion
import django.utils.timezone
import surveys.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_encuesta_requiere_ubicacion_pregunta_activa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto Libre'), ('numero', 'Numérico'), ('opciones', 'Opciones'), ('foto', 'Foto'), ('fecha', 'Fecha')], default='texto', max_length=20),
        ),
        migrations.AlterField(
            model_name='respuestaheader',
            name='fecha_envio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='RespuestaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=surveys.models.generar_ruta_imagen)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_extra', to='surveys.respuestadetalle')),
            ],
        ),
    ]
