# Generated by Django 6.0.1 on 2026-01-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_alter_pregunta_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='incluir_fecha',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto Libre'), ('numero', 'Numérico'), ('opciones', 'Opciones'), ('foto', 'Foto')], default='texto', max_length=20),
        ),
    ]
