# Generated by Django 6.0.1 on 2026-01-27 11:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_encuesta_incluir_fecha_alter_pregunta_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
