# Generated by Django 6.0.1 on 2026-01-27 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_alter_encuesta_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=20, unique=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto Libre'), ('numero', 'Numérico'), ('opciones', 'Opciones'), ('telefono', 'Teléfono (+54)'), ('foto', 'Foto')], default='texto', max_length=20),
        ),
        migrations.AddField(
            model_name='respuestaheader',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_asociadas', to='surveys.contacto'),
        ),
    ]
