# Generated by Django 6.0.1 on 2026-01-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_contacto_alter_pregunta_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='tag',
            field=models.CharField(default='Encuesta', max_length=100),
        ),
    ]
