# Generated by Django 6.0.1 on 2026-01-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_contacto_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='tag',
            field=models.CharField(blank=True, default='Manual', max_length=100, null=True),
        ),
    ]
