# Generated by Django 6.0.1 on 2026-01-27 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_alter_contacto_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='tag',
            field=models.CharField(default='encuesta', max_length=50),
        ),
        migrations.AlterField(
            model_name='respuestaheader',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encuestas_respondidas', to='surveys.contacto'),
        ),
    ]
