# Generated by Django 6.0.1 on 2026-01-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_alter_contacto_tag_alter_respuestaheader_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto Libre'), ('numero', 'Numérico'), ('opciones', 'Opciones'), ('telefono', 'Teléfono (Legacy)'), ('foto', 'Foto'), ('nombre', 'Nombre Completo'), ('celular', 'Celular'), ('dni', 'DNI'), ('mail', 'Email')], default='texto', max_length=20),
        ),
    ]
