# Generated by Django 6.0.1 on 2026-02-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_contacto_dni_contacto_email_alter_pregunta_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='permitir_multiple',
            field=models.BooleanField(default=False),
        ),
    ]
