# Generated by Django 6.0.1 on 2026-02-02 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_pregunta_permitir_multiple'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='permitir_multiple',
            new_name='permite_multiple',
        ),
    ]
