# Generated by Django 6.0.1 on 2026-02-02 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_rename_permitir_multiple_pregunta_permite_multiple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestadetalle',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_recibidas', to='surveys.pregunta'),
        ),
        migrations.AlterField(
            model_name='respuestaheader',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='surveys.encuesta'),
        ),
    ]
