# Generated by Django 6.0.1 on 2026-02-11 20:20

import django.db.models.deletion
from django.db import migrations, models



def unbind_contacts(apps, schema_editor):
    # Rompemos la relación con los contactos viejos para evitar error de FK
    # al cambiar a la tabla nueva (que está vacía).
    RespuestaHeader = apps.get_model('surveys', 'RespuestaHeader')
    RespuestaHeader.objects.all().update(contacto=None)

class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
        ('surveys', '0013_alter_respuestadetalle_pregunta_and_more'),
    ]

    operations = [
        migrations.RunPython(unbind_contacts, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='respuestaheader',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encuestas_respondidas', to='contact.contacto'),
        ),
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
