# Generated by Django 6.0.1 on 2026-02-13 03:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0014_alter_respuestaheader_contacto_delete_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestaheader',
            name='fecha_envio',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
