# Generated by Django 6.0.1 on 2026-02-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0015_alter_respuestaheader_fecha_envio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(upload_to='relevamientos/fotos/')),
                ('respuesta_id', models.IntegerField(help_text='ID de la respuesta original')),
                ('encuesta_id', models.IntegerField(help_text='ID de la encuesta a la que pertenece')),
                ('barrio', models.CharField(blank=True, max_length=100, null=True)),
                ('seccion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'indexes': [models.Index(fields=['barrio', 'seccion'], name='surveys_fot_barrio_fe481b_idx'), models.Index(fields=['fecha'], name='surveys_fot_fecha_e25b8d_idx')],
            },
        ),
    ]
