# Generated by Django 6.0.1 on 2026-02-18 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0016_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestadetalle',
            name='valor_foto',
        ),
    ]
