# Generated by Django 6.0.1 on 2026-02-18 11:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0017_remove_respuestadetalle_valor_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
