# Generated by Django 6.0.1 on 2026-03-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0018_alter_foto_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foto',
            options={'ordering': ['-fecha', '-id'], 'verbose_name': 'Foto', 'verbose_name_plural': 'Fotos'},
        ),
        migrations.AddField(
            model_name='encuesta',
            name='activar_encuestador_manual',
            field=models.BooleanField(default=False),
        ),
    ]
