# Generated by Django 6.0.1 on 2026-04-09 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0019_alter_foto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barrio',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='seccion',
            options={'ordering': ['nombre']},
        ),
    ]
