# Generated by Django 6.0.1 on 2026-05-02 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0020_alter_barrio_options_alter_seccion_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('orden', models.IntegerField(default=0)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='surveys.encuesta')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='grupo',
            field=models.ForeignKey(blank=True, help_text='Grupo al que pertenece para visualización agrupada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas', to='surveys.grupo'),
        ),
    ]
