# Generated by Django 6.0.1 on 2026-04-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='tag',
            field=models.CharField(default='encuesta', max_length=255),
        ),
    ]
